version: '3.8'

services:
  # PostgreSQL Database Service
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # pgAdmin Service (Web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

  # PHP Application Service (with Apache)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: my_php_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      # If you need custom php.ini settings:
      # - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      # If you need custom Apache configuration:
      # - ./apache/my-custom-site.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      DB_HOST: postgres # Service name of the PostgreSQL container
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}         # From .env file
      DB_USER: ${POSTGRES_USER}         # From .env file
      DB_PASSWORD: ${POSTGRES_PASSWORD} # From .env file
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge
